# 매매일지 — 2026-06-12 코호트 (D+1 부분판정)

> 양식: `../daily_trade_journal_format_6_13.md` (5블록)
> ★ 봇 OFF / paper 기준 / 실주문 0 · picks 불변 · SAJANG 무변경 ★
> 작성: 2026-06-15(월) 장 마감 후 / forward 충전: VPS nightly 18:04 (24건)
> 데이터 출처: **VPS 운영본** ledger_2026-06-12.json (B14·C10). ※노트북 로컬본은 B18·C13 — 6/12 당일 양쪽 각자 선정으로 종목수 불일치, 별도 규명 대상(타입 비교라 결론 무영향).

---

## [0] 시장
- **진입일 6/12(금)**: breadth 0.724 BROAD_UP (상승 2,821 / 하락 780) / 삼성전자 +7.86% / 주도 = 반도체·AI / 상한가 15
- **결과일 6/15(월)**: 삼성전자 322,500 → 337,000 (**+4.5%**) — 강세 이어짐. 삼성전기 +16.6%(MLCC 주도)

## [1] 오늘 본 종목 (B=강한섹터 눌림 / C=강한섹터 올라타기)
- 6/12 코호트 = B 14종목, C 10종목 (반도체/AI · 건설 · 화장품 섹터)
- 목표 = 트레일링 고점 −3% / 손절 = 진입 −3% (SAJANG)

## [2] forward — D+1 (= 6/15 종가, 진입=6/12 종가 기준). ※ d3·d5는 6/16·6/18 발생

### B타입 (눌림, 14종목) — 평균 D+1 **+0.55%** / 승률 9/14 (64%)
| 종목 | 섹터 | D+1 | MFE | MAE |
|---|---|---|---|---|
| DL이앤씨(375500) | 건설 | +6.9 | 11.6 | +3.7 |
| SK하이닉스(000660) | 반도체 | +6.42 | 8.0 | **+5.4** |
| GS건설(006360) | 건설 | +5.03 | 9.6 | +3.1 |
| 삼성전자(005930) | 반도체 | +4.5 | 6.8 | +3.6 |
| SK스퀘어(402340) | 반도체 | +4.05 | 6.3 | -0.2 |
| HDC현산(294870) | 건설 | +2.41 | 4.2 | +1.2 |
| LG생활건강(051900) | 화장품 | +1.86 | 3.1 | +0.8 |
| 아모레퍼시픽(090430) | 화장품 | +0.45 | 2.5 | -0.3 |
| 코스맥스(192820) | 화장품 | +0.06 | 3.0 | -0.2 |
| 클리오(237880) | 화장품 | -0.56 | 1.5 | -0.9 |
| 솔브레인(357780) | 반도체 | -3.28 | 3.9 | -4.3 |
| 한미반도체(042700) | 반도체 | -3.88 | 2.1 | -5.0 |
| 리노공업(058470) | 반도체 | -7.37 | 3.1 | -7.6 |
| ISC(095340) | 반도체 | -8.91 | 1.1 | -10.0 |

### C타입 (추격, 10종목) — 평균 D+1 **-1.57%** / 승률 4/10 (40%)
| 종목 | 섹터 | D+1 | MAE |
|---|---|---|---|
| DL이앤씨(375500) | 건설 | +6.9 | +3.7 |
| GS건설(006360) | 건설 | +5.03 | +3.1 |
| 삼성전자(005930) | 반도체 | +4.5 | +3.6 |
| SK스퀘어(402340) | 반도체 | +4.05 | -0.2 |
| 솔브레인(357780) | 반도체 | -3.28 | -4.3 |
| 한미반도체(042700) | 반도체 | -3.88 | -5.0 |
| 원익IPS(240810) | 반도체 | **-4.8** | -7.9 |
| 리노공업(058470) | 반도체 | -7.37 | -7.6 |
| 현대건설(000720) | 건설 | **-7.94** | -9.9 |
| ISC(095340) | 반도체 | **-8.91** | -10.0 |

### 트레일링 −3% 적용 시 (거친 근사: MAE ≤ -3% 종목은 -3%에서 청산 가정)
| | raw D+1 (보유) | 트레일 -3% 적용 |
|---|---|---|
| B (눌림) | +0.55% | **+1.37%** |
| C (추격) | -1.57% | **+0.25%** |

## [3] 복기
- **잘 본 것 — B(눌림) > C(추격), 차이 +2.1%p.** 6/12 강세장 **다음날 대형 눌림이 더 갔다**: 삼성전자(+4.5)·SK하이닉스(+6.42, MAE +5.35 = 한 번도 마이너스 안 감), 건설 눌림(DL +6.9·GS +5.03)도 강세.
- **틀린 것 — C 추격은 약했다.** 6/12 폭등 장비주를 추격 진입했으면 손실: 원익IPS -4.8·ISC -8.91·현대건설 -7.94. "고점 추격" 리스크 데이터 확인.
- **트레일 −3% 효과**: 적용 시 B·C **둘 다 양수**(B+1.37 / C+0.25). 특히 C(추격)가 -1.57→+0.25로 **손실 방어** = 타이트 손절의 값어치(매매스타일 검증 ① -3% 유지와 동일 방향).
- **"터지기 전" 패턴**: *강세장 다음날 = 대형 눌림(20일선 지지) > 중소 추격*. → **이평선 게이트 후보(20일선 지지 눌림 승격) 가설 지지하는 첫 forward 데이터**.
- **특이**: ISC(반도체 장비)는 B·C 양쪽 선정인데 -8.91로 최악 — 양쪽 끼었어도 못 감. / SK하이닉스 = HBM 대장, 외인 순매수 +1,155억(아침 F1 2위), MAE 내내 양수 = 안정적 대장의 표본.
- **다음 관찰**: d3·d5(6/16·6/18) → B 우위 지속 시 이평선 게이트 검증 진척. SK하이닉스 추세 지속 여부.

## [4] 안전
봇 OFF ✅ / 실주문 0 ✅ / picks 불변 ✅ / SAJANG 무변경 ✅ / 판정 read-only ✅

---

## 판정 (부분 = D+1만)
- **경향: B(눌림 매수) 우위** — 평균·승률·트레일 청산 모두 B 우위
- **KEEP (관측 지속)** — d3·d5 확인 후 확정. D+1 하나라 미확정.
- **후속**: ① d3·d5 forward 충전(자동 nightly) ② 노트북/VPS ledger 불일치 규명 ③ 이평선 게이트 후보 검증 연결
